"""discounts split payment customers credit

Revision ID: 159f8fea95a7
Revises: 3e72290e9f62
Create Date: 2026-10-03 23:00:51.003025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '159f8fea95a7'
down_revision: Union[str, Sequence[str], None] = '3e72290e9f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'phone', name='uq_customers_phone')
    )
    op.create_index(op.f('ix_customers_shop_id'), 'customers', ['shop_id'], unique=False)
    op.create_table('credit_repayments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("mode IN ('cash', 'upi', 'card')", name='ck_credit_repayments_mode'),
    sa.CheckConstraint('amount_paise > 0', name='ck_credit_repayments_amount'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_repayments_business_date'), 'credit_repayments', ['business_date'], unique=False)
    op.create_index(op.f('ix_credit_repayments_customer_id'), 'credit_repayments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credit_repayments_shift_id'), 'credit_repayments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_credit_repayments_shop_id'), 'credit_repayments', ['shop_id'], unique=False)
    op.add_column('bill_lines', sa.Column('discount_paise', sa.Integer(), server_default='0', nullable=False))
    op.add_column('bills', sa.Column('order_part', sa.SmallInteger(), server_default='1', nullable=False))
    op.add_column('bills', sa.Column('discount_paise', sa.Integer(), server_default='0', nullable=False))
    op.add_column('bills', sa.Column('discount_reason', sa.String(length=200), server_default='', nullable=False))
    op.add_column('bills', sa.Column('payment_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bills', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('bills', sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_index(op.f('uq_bills_order_id'), table_name='bills', postgresql_where='(order_id IS NOT NULL)')
    op.create_index('uq_bills_order_id', 'bills', ['order_id', 'order_part'], unique=True, postgresql_where=sa.text('order_id IS NOT NULL'))
    op.create_index(op.f('ix_bills_customer_id'), 'bills', ['customer_id'], unique=False)
    op.create_foreign_key('bills_customer_id_fkey', 'bills', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.add_column('shops', sa.Column('max_discount_bp', sa.Integer(), server_default='1000', nullable=False))
    # ### end Alembic commands ###
    # Two more ways to pay. Allowed inside a transaction on Postgres 12+; nothing in
    # this migration uses the new values, which is the one restriction there.
    op.execute("ALTER TYPE payment_mode ADD VALUE IF NOT EXISTS 'split'")
    op.execute("ALTER TYPE payment_mode ADD VALUE IF NOT EXISTS 'credit'")
    # Deny-by-default for Supabase's Data API (see d9b48b507dcc).
    for t in ("customers", "credit_repayments"):
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'max_discount_bp')
    op.drop_constraint('bills_customer_id_fkey', 'bills', type_='foreignkey')
    op.drop_index(op.f('ix_bills_customer_id'), table_name='bills')
    op.drop_index('uq_bills_order_id', table_name='bills', postgresql_where=sa.text('order_id IS NOT NULL'))
    op.create_index(op.f('uq_bills_order_id'), 'bills', ['order_id'], unique=True, postgresql_where='(order_id IS NOT NULL)')
    op.drop_column('bills', 'flags')
    op.drop_column('bills', 'customer_id')
    op.drop_column('bills', 'payment_parts')
    op.drop_column('bills', 'discount_reason')
    op.drop_column('bills', 'discount_paise')
    op.drop_column('bills', 'order_part')
    op.drop_column('bill_lines', 'discount_paise')
    op.drop_index(op.f('ix_credit_repayments_shop_id'), table_name='credit_repayments')
    op.drop_index(op.f('ix_credit_repayments_shift_id'), table_name='credit_repayments')
    op.drop_index(op.f('ix_credit_repayments_customer_id'), table_name='credit_repayments')
    op.drop_index(op.f('ix_credit_repayments_business_date'), table_name='credit_repayments')
    op.drop_table('credit_repayments')
    op.drop_index(op.f('ix_customers_shop_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
    # Postgres cannot drop a value from an enum type. 'split' and 'credit' stay on
    # payment_mode; nothing older uses them, and upgrading again skips them (IF NOT
    # EXISTS). The type itself is dropped with the bills table at base.
