"""stock openings

Revision ID: 186b480b47fc
Revises: acf0595d9746
Create Date: 2026-10-03 11:07:25.206468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '186b480b47fc'
down_revision: Union[str, Sequence[str], None] = 'acf0595d9746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_openings',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('entered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loose_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('system_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('counted_by', sa.UUID(), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('counted_qty >= 0', name='ck_stock_openings_counted'),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'ingredient_id', name='uq_stock_openings_ingredient')
    )
    op.create_index(op.f('ix_stock_openings_shop_id'), 'stock_openings', ['shop_id'], unique=False)
    # ### end Alembic commands ###
    # Deny-by-default for Supabase's Data API (see d9b48b507dcc).
    op.execute("ALTER TABLE stock_openings ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_openings_shop_id'), table_name='stock_openings')
    op.drop_table('stock_openings')
    # ### end Alembic commands ###
