"""phase1 catalogue recipes stock ledger

Revision ID: 25dd3fc29c46
Revises: f65f53f1ca51
Create Date: 2026-10-03 07:07:56.362111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25dd3fc29c46'
down_revision: Union[str, Sequence[str], None] = 'f65f53f1ca51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('raw', 'prep', name='ingredient_kind'), nullable=False),
    sa.Column('base_unit', sa.Enum('ml', 'g', 'piece', name='base_unit'), nullable=False),
    sa.Column('cost_per_unit_paise', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('tolerance_bp', sa.Integer(), nullable=False),
    sa.Column('count_frequency', sa.String(length=10), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_ingredients_shop_name')
    )
    op.create_index(op.f('ix_ingredients_shop_id'), 'ingredients', ['shop_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('hsn_sac', sa.String(length=8), nullable=False),
    sa.Column('gst_rate_bp', sa.Integer(), nullable=False),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('price_paise >= 0', name='ck_menu_items_price'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_menu_items_shop_name')
    )
    op.create_index(op.f('ix_menu_items_shop_id'), 'menu_items', ['shop_id'], unique=False)
    op.create_table('modifiers',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('price_delta_paise', sa.Integer(), nullable=False),
    sa.Column('scale_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('scale_factor > 0', name='ck_modifiers_scale'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_modifiers_shop_name')
    )
    op.create_index(op.f('ix_modifiers_shop_id'), 'modifiers', ['shop_id'], unique=False)
    op.create_table('menu_item_modifiers',
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('modifier_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id', 'modifier_id', name='uq_menu_item_modifiers')
    )
    op.create_index(op.f('ix_menu_item_modifiers_menu_item_id'), 'menu_item_modifiers', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_menu_item_modifiers_shop_id'), 'menu_item_modifiers', ['shop_id'], unique=False)
    op.create_table('modifier_lines',
    sa.Column('modifier_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('qty_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modifier_id', 'ingredient_id', name='uq_modifier_lines_ingredient')
    )
    op.create_index(op.f('ix_modifier_lines_modifier_id'), 'modifier_lines', ['modifier_id'], unique=False)
    op.create_index(op.f('ix_modifier_lines_shop_id'), 'modifier_lines', ['shop_id'], unique=False)
    op.create_table('pack_units',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('qty_in_base', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('qty_in_base > 0', name='ck_pack_units_positive'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'name', name='uq_pack_units_ingredient_name')
    )
    op.create_index(op.f('ix_pack_units_ingredient_id'), 'pack_units', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_pack_units_shop_id'), 'pack_units', ['shop_id'], unique=False)
    op.create_table('recipes',
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('prep_ingredient_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yield_qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('yield_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(menu_item_id IS NULL) <> (prep_ingredient_id IS NULL)', name='ck_recipes_one_output'),
    sa.CheckConstraint('(prep_ingredient_id IS NULL) OR (yield_qty > 0)', name='ck_recipes_prep_yield'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prep_ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id', 'version', name='uq_recipes_menu_item_version'),
    sa.UniqueConstraint('prep_ingredient_id', 'version', name='uq_recipes_prep_version')
    )
    op.create_index(op.f('ix_recipes_menu_item_id'), 'recipes', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_recipes_prep_ingredient_id'), 'recipes', ['prep_ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipes_shop_id'), 'recipes', ['shop_id'], unique=False)
    op.create_table('stock_ledger',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('qty_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.Enum('opening', 'stock_in', 'sale', 'prep_in', 'prep_out', 'void', 'wastage', 'count_adjustment', name='ledger_reason'), nullable=False),
    sa.Column('ref_type', sa.String(length=30), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('qty_delta <> 0', name='ck_stock_ledger_nonzero'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ledger_business_date'), 'stock_ledger', ['business_date'], unique=False)
    op.create_index(op.f('ix_stock_ledger_shop_id'), 'stock_ledger', ['shop_id'], unique=False)
    op.create_index('ix_stock_ledger_shop_ingredient', 'stock_ledger', ['shop_id', 'ingredient_id'], unique=False)
    op.create_table('stock_receipts',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('supplier', sa.String(length=80), nullable=False),
    sa.Column('entered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loose_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('base_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('cost_paise', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('base_qty > 0', name='ck_stock_receipts_positive'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_receipts_ingredient_id'), 'stock_receipts', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_stock_receipts_shop_id'), 'stock_receipts', ['shop_id'], unique=False)
    op.create_table('prep_batches',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('batches', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('made_by', sa.UUID(), nullable=False),
    sa.Column('made_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('batches > 0', name='ck_prep_batches_positive'),
    sa.ForeignKeyConstraint(['made_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prep_batches_shop_id'), 'prep_batches', ['shop_id'], unique=False)
    op.create_table('recipe_lines',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('qty > 0', name='ck_recipe_lines_positive'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'ingredient_id', name='uq_recipe_lines_ingredient')
    )
    op.create_index(op.f('ix_recipe_lines_recipe_id'), 'recipe_lines', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_lines_shop_id'), 'recipe_lines', ['shop_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: the stock ledger is append-only, enforced by the database
    # itself so no future bug or ad-hoc SQL can rewrite stock history.
    op.execute("""
        CREATE FUNCTION stock_ledger_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'stock_ledger is append-only: % is not allowed. '
                'Correct mistakes with a count_adjustment row.', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER stock_ledger_no_update_delete
        BEFORE UPDATE OR DELETE ON stock_ledger
        FOR EACH ROW EXECUTE FUNCTION stock_ledger_append_only();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS stock_ledger_no_update_delete ON stock_ledger")
    op.execute("DROP FUNCTION IF EXISTS stock_ledger_append_only()")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_lines_shop_id'), table_name='recipe_lines')
    op.drop_index(op.f('ix_recipe_lines_recipe_id'), table_name='recipe_lines')
    op.drop_table('recipe_lines')
    op.drop_index(op.f('ix_prep_batches_shop_id'), table_name='prep_batches')
    op.drop_table('prep_batches')
    op.drop_index(op.f('ix_stock_receipts_shop_id'), table_name='stock_receipts')
    op.drop_index(op.f('ix_stock_receipts_ingredient_id'), table_name='stock_receipts')
    op.drop_table('stock_receipts')
    op.drop_index('ix_stock_ledger_shop_ingredient', table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_shop_id'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_business_date'), table_name='stock_ledger')
    op.drop_table('stock_ledger')
    op.drop_index(op.f('ix_recipes_shop_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_prep_ingredient_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_menu_item_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_pack_units_shop_id'), table_name='pack_units')
    op.drop_index(op.f('ix_pack_units_ingredient_id'), table_name='pack_units')
    op.drop_table('pack_units')
    op.drop_index(op.f('ix_modifier_lines_shop_id'), table_name='modifier_lines')
    op.drop_index(op.f('ix_modifier_lines_modifier_id'), table_name='modifier_lines')
    op.drop_table('modifier_lines')
    op.drop_index(op.f('ix_menu_item_modifiers_shop_id'), table_name='menu_item_modifiers')
    op.drop_index(op.f('ix_menu_item_modifiers_menu_item_id'), table_name='menu_item_modifiers')
    op.drop_table('menu_item_modifiers')
    op.drop_index(op.f('ix_modifiers_shop_id'), table_name='modifiers')
    op.drop_table('modifiers')
    op.drop_index(op.f('ix_menu_items_shop_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_ingredients_shop_id'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
    # Hand-written: autogenerate never drops Postgres enum types.
    op.execute("DROP TYPE IF EXISTS ledger_reason")
    op.execute("DROP TYPE IF EXISTS base_unit")
    op.execute("DROP TYPE IF EXISTS ingredient_kind")
