"""tablet health reports

Revision ID: 29eaae940a0a
Revises: bf5d2d3d711c
Create Date: 2026-10-03 18:18:39.490558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29eaae940a0a'
down_revision: Union[str, Sequence[str], None] = 'bf5d2d3d711c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('reported_seq_by_fy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('devices', sa.Column('health', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('devices', sa.Column('health_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'health_at')
    op.drop_column('devices', 'health')
    op.drop_column('devices', 'reported_seq_by_fy')
    # ### end Alembic commands ###
