"""bill voids

Revision ID: 37753b716b02
Revises: 584c31af830a
Create Date: 2026-10-03 14:44:42.655682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37753b716b02'
down_revision: Union[str, Sequence[str], None] = '584c31af830a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_voids',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('wrong_item', 'duplicate', 'payment_failed', 'customer_cancelled', 'other', name='void_reason'), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('stock_returned', sa.Boolean(), nullable=False),
    sa.Column('voided_by', sa.UUID(), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', name='uq_bill_voids_bill')
    )
    op.create_index(op.f('ix_bill_voids_shop_id'), 'bill_voids', ['shop_id'], unique=False)
    # ### end Alembic commands ###
    # Deny-by-default for Supabase's Data API (see d9b48b507dcc).
    op.execute("ALTER TABLE bill_voids ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_voids_shop_id'), table_name='bill_voids')
    op.drop_table('bill_voids')
    # ### end Alembic commands ###
    sa.Enum(name="void_reason").drop(op.get_bind(), checkfirst=True)
