"""tables and running orders

Revision ID: 3e72290e9f62
Revises: 29eaae940a0a
Create Date: 2026-10-03 19:59:09.515452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e72290e9f62'
down_revision: Union[str, Sequence[str], None] = '29eaae940a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_areas',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_dining_areas_name')
    )
    op.create_index(op.f('ix_dining_areas_shop_id'), 'dining_areas', ['shop_id'], unique=False)
    op.create_table('dining_tables',
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['dining_areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_dining_tables_name')
    )
    op.create_index(op.f('ix_dining_tables_area_id'), 'dining_tables', ['area_id'], unique=False)
    op.create_index(op.f('ix_dining_tables_shop_id'), 'dining_tables', ['shop_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.Enum('dine_in', 'takeaway', 'delivery', name='order_type'), nullable=False),
    sa.Column('status', sa.Enum('open', 'billed', 'settled', 'cancelled', name='order_status'), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['table_id'], ['dining_tables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_shop_business_date', 'orders', ['shop_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_orders_shop_id'), 'orders', ['shop_id'], unique=False)
    op.create_index('ix_orders_shop_status', 'orders', ['shop_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    op.create_index(op.f('ix_orders_updated_at'), 'orders', ['updated_at'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('open', 'kot', 'cancel', 'move', 'details', 'bill_printed', 'ready', 'settle', 'cancel_order', name='order_event_kind'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('by', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_events_shop_id'), 'order_events', ['shop_id'], unique=False)
    op.add_column('bills', sa.Column('order_id', sa.UUID(), nullable=True))
    op.create_index('uq_bills_order_id', 'bills', ['order_id'], unique=True, postgresql_where=sa.text('order_id IS NOT NULL'))
    op.create_foreign_key('bills_order_id_fkey', 'bills', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
    # Deny-by-default for Supabase's Data API (see d9b48b507dcc).
    for t in ("dining_areas", "dining_tables", "orders", "order_events"):
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
    # Order history is append-only, like the stock ledger: corrections are new events.
    op.execute("""
        CREATE FUNCTION order_events_append_only() RETURNS trigger
        SET search_path = '' AS $$
        BEGIN
            RAISE EXCEPTION 'order_events is append-only: % is not allowed. '
                'Correct an order with a new event.', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER order_events_no_update_delete
        BEFORE UPDATE OR DELETE ON order_events
        FOR EACH ROW EXECUTE FUNCTION order_events_append_only();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS order_events_no_update_delete ON order_events")
    op.execute("DROP FUNCTION IF EXISTS order_events_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('bills_order_id_fkey', 'bills', type_='foreignkey')
    op.drop_index('uq_bills_order_id', table_name='bills', postgresql_where=sa.text('order_id IS NOT NULL'))
    op.drop_column('bills', 'order_id')
    op.drop_index(op.f('ix_order_events_shop_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_orders_updated_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_index('ix_orders_shop_status', table_name='orders')
    op.drop_index(op.f('ix_orders_shop_id'), table_name='orders')
    op.drop_index('ix_orders_shop_business_date', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dining_tables_shop_id'), table_name='dining_tables')
    op.drop_index(op.f('ix_dining_tables_area_id'), table_name='dining_tables')
    op.drop_table('dining_tables')
    op.drop_index(op.f('ix_dining_areas_shop_id'), table_name='dining_areas')
    op.drop_table('dining_areas')
    # ### end Alembic commands ###
    for name in ("order_event_kind", "order_status", "order_type"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
