"""email outbox and report settings

Revision ID: 584c31af830a
Revises: e224eddd7638
Create Date: 2026-10-03 13:31:24.878157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '584c31af830a'
down_revision: Union[str, Sequence[str], None] = 'e224eddd7638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('kind', sa.Enum('bill', 'day_end', 'daily', 'weekly', 'test', name='email_kind'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('to_email', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='email_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'dedupe_key', name='uq_email_outbox_dedupe')
    )
    op.create_index(op.f('ix_email_outbox_shop_id'), 'email_outbox', ['shop_id'], unique=False)
    op.create_index(op.f('ix_email_outbox_status'), 'email_outbox', ['status'], unique=False)
    op.add_column('shops', sa.Column('report_email', sa.String(length=254), nullable=True))
    op.add_column('shops', sa.Column('email_each_bill', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('shops', sa.Column('email_day_end', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('shops', sa.Column('email_daily', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('shops', sa.Column('email_weekly', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###
    # Deny-by-default for Supabase's Data API (see d9b48b507dcc).
    op.execute("ALTER TABLE email_outbox ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'email_weekly')
    op.drop_column('shops', 'email_daily')
    op.drop_column('shops', 'email_day_end')
    op.drop_column('shops', 'email_each_bill')
    op.drop_column('shops', 'report_email')
    op.drop_index(op.f('ix_email_outbox_status'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_shop_id'), table_name='email_outbox')
    op.drop_table('email_outbox')
    # ### end Alembic commands ###
    sa.Enum(name="email_kind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="email_status").drop(op.get_bind(), checkfirst=True)
