"""online payments

Revision ID: 59c516ec02c9
Revises: 3e72290e9f62
Create Date: 2026-10-03 22:24:27.277540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c516ec02c9'
down_revision: Union[str, Sequence[str], None] = '3e72290e9f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('paid_paise', sa.Integer(), nullable=True),
    sa.Column('provider_order_id', sa.String(length=40), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=40), nullable=True),
    sa.Column('error', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("method IN ('upi', 'card')", name='ck_payments_method'),
    sa.CheckConstraint("status IN ('created', 'paid', 'failed')", name='ck_payments_status'),
    sa.CheckConstraint('amount_paise > 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_order_id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payments_shop_id'), 'payments', ['shop_id'], unique=False)
    # ### end Alembic commands ###
    # Deny-by-default for Supabase's Data API (see d9b48b507dcc).
    op.execute("ALTER TABLE payments ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_shop_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
