"""ingredient scales_with_size

Revision ID: acf0595d9746
Revises: e90e30ec5782
Create Date: 2026-10-03 10:53:37.581210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf0595d9746'
down_revision: Union[str, Sequence[str], None] = 'e90e30ec5782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('scales_with_size', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'scales_with_size')
    # ### end Alembic commands ###
