"""shifts and cash

Revision ID: bf5d2d3d711c
Revises: 0738a5fd515c
Create Date: 2026-10-03 17:51:35.665018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5d2d3d711c'
down_revision: Union[str, Sequence[str], None] = '0738a5fd515c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('opening_float_paise', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counted_cash_paise', sa.Integer(), nullable=True),
    sa.Column('close_note', sa.String(length=200), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('counted_cash_paise >= 0', name='ck_shifts_counted'),
    sa.CheckConstraint('opening_float_paise >= 0', name='ck_shifts_float'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_device_id'), 'shifts', ['device_id'], unique=False)
    op.create_index('ix_shifts_shop_business_date', 'shifts', ['shop_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_shifts_shop_id'), 'shifts', ['shop_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('pay_out', 'pay_in', name='cash_movement_kind'), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount_paise > 0', name='ck_cash_movements_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_shift_id'), 'cash_movements', ['shift_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_shop_id'), 'cash_movements', ['shop_id'], unique=False)
    op.add_column('bills', sa.Column('shift_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_bills_shift_id'), 'bills', ['shift_id'], unique=False)
    op.create_foreign_key('bills_shift_id_fkey', 'bills', 'shifts', ['shift_id'], ['id'], ondelete='RESTRICT')
    op.add_column('shops', sa.Column('cash_shifts', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###
    # Deny-by-default for Supabase's Data API (see d9b48b507dcc).
    op.execute("ALTER TABLE shifts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE cash_movements ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'cash_shifts')
    op.drop_constraint('bills_shift_id_fkey', 'bills', type_='foreignkey')
    op.drop_index(op.f('ix_bills_shift_id'), table_name='bills')
    op.drop_column('bills', 'shift_id')
    op.drop_index(op.f('ix_cash_movements_shop_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_shift_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_shifts_shop_id'), table_name='shifts')
    op.drop_index('ix_shifts_shop_business_date', table_name='shifts')
    op.drop_index(op.f('ix_shifts_device_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
    sa.Enum(name="cash_movement_kind").drop(op.get_bind(), checkfirst=True)
