"""wastage and day counts

Revision ID: e224eddd7638
Revises: 186b480b47fc
Create Date: 2026-10-03 12:18:15.452221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e224eddd7638'
down_revision: Union[str, Sequence[str], None] = '186b480b47fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_counts',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('counting', 'submitted', 'approved', name='day_count_status'), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'business_date', name='uq_day_counts_date')
    )
    op.create_index(op.f('ix_day_counts_shop_id'), 'day_counts', ['shop_id'], unique=False)
    op.create_table('day_count_lines',
    sa.Column('day_count_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('entered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loose_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('recount_requested', sa.Boolean(), nullable=False),
    sa.Column('recounted', sa.Boolean(), nullable=False),
    sa.Column('counted_by', sa.UUID(), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('cost_per_unit_paise', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('variance_paise', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('counted_qty >= 0', name='ck_day_count_lines_counted'),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['day_count_id'], ['day_counts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_count_id', 'ingredient_id', name='uq_day_count_lines_ingredient')
    )
    op.create_index(op.f('ix_day_count_lines_day_count_id'), 'day_count_lines', ['day_count_id'], unique=False)
    op.create_index(op.f('ix_day_count_lines_shop_id'), 'day_count_lines', ['shop_id'], unique=False)
    op.create_table('wastage_entries',
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.Enum('spoiled', 'spilled', 'remake', 'prep_loss', 'staff', 'complimentary', 'theft', name='wastage_reason'), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('value_paise', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(ingredient_id IS NULL) <> (menu_item_id IS NULL)', name='ck_wastage_one_target'),
    sa.CheckConstraint('qty > 0', name='ck_wastage_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wastage_entries_business_date'), 'wastage_entries', ['business_date'], unique=False)
    op.create_index(op.f('ix_wastage_entries_shop_id'), 'wastage_entries', ['shop_id'], unique=False)
    # ### end Alembic commands ###
    # Deny-by-default for Supabase's Data API (see d9b48b507dcc).
    for table in ("wastage_entries", "day_counts", "day_count_lines"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wastage_entries_shop_id'), table_name='wastage_entries')
    op.drop_index(op.f('ix_wastage_entries_business_date'), table_name='wastage_entries')
    op.drop_table('wastage_entries')
    op.drop_index(op.f('ix_day_count_lines_shop_id'), table_name='day_count_lines')
    op.drop_index(op.f('ix_day_count_lines_day_count_id'), table_name='day_count_lines')
    op.drop_table('day_count_lines')
    op.drop_index(op.f('ix_day_counts_shop_id'), table_name='day_counts')
    op.drop_table('day_counts')
    # ### end Alembic commands ###
    sa.Enum(name="wastage_reason").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="day_count_status").drop(op.get_bind(), checkfirst=True)
