"""phase2a bills

Revision ID: e90e30ec5782
Revises: 2813bf31e0c6
Create Date: 2026-10-03 08:43:36.425064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e90e30ec5782'
down_revision: Union[str, Sequence[str], None] = '2813bf31e0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('cashier_id', sa.UUID(), nullable=False),
    sa.Column('fy', sa.String(length=5), nullable=False),
    sa.Column('local_seq', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=16), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.Enum('cash', 'upi', 'card', name='payment_mode'), nullable=False),
    sa.Column('status', sa.Enum('completed', 'void', name='bill_status'), nullable=False),
    # gst_type already exists (shops table): reuse it, don't CREATE it again.
    sa.Column('gst_type', postgresql.ENUM(name='gst_type', create_type=False), nullable=False),
    sa.Column('taxable_paise', sa.Integer(), nullable=False),
    sa.Column('cgst_paise', sa.Integer(), nullable=False),
    sa.Column('sgst_paise', sa.Integer(), nullable=False),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.Column('round_off_paise', sa.Integer(), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('server_totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('totals_mismatch', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('local_seq >= 1', name='ck_bills_seq'),
    sa.CheckConstraint('total_paise >= 0', name='ck_bills_total'),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'device_id', 'fy', 'local_seq', name='uq_bills_device_seq'),
    sa.UniqueConstraint('shop_id', 'invoice_no', name='uq_bills_invoice_no')
    )
    op.create_index(op.f('ix_bills_device_id'), 'bills', ['device_id'], unique=False)
    op.create_index('ix_bills_shop_business_date', 'bills', ['shop_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_bills_shop_id'), 'bills', ['shop_id'], unique=False)
    op.create_index(op.f('ix_bills_totals_mismatch'), 'bills', ['totals_mismatch'], unique=False)
    op.create_table('bill_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=80), nullable=False),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('gst_rate_bp', sa.Integer(), nullable=False),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('gross_paise', sa.Integer(), nullable=False),
    sa.Column('taxable_paise', sa.Integer(), nullable=False),
    sa.Column('cgst_paise', sa.Integer(), nullable=False),
    sa.Column('sgst_paise', sa.Integer(), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('qty >= 1', name='ck_bill_lines_qty'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'position', name='uq_bill_lines_position')
    )
    op.create_index(op.f('ix_bill_lines_bill_id'), 'bill_lines', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_lines_shop_id'), 'bill_lines', ['shop_id'], unique=False)
    op.create_table('bill_line_modifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_line_id', sa.UUID(), nullable=False),
    sa.Column('modifier_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=40), nullable=False),
    sa.Column('price_delta_paise', sa.Integer(), nullable=False),
    sa.Column('scale_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('lines_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bill_line_id'], ['bill_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_line_modifiers_bill_line_id'), 'bill_line_modifiers', ['bill_line_id'], unique=False)
    op.create_index(op.f('ix_bill_line_modifiers_shop_id'), 'bill_line_modifiers', ['shop_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: deny-by-default for Supabase's Data API (see d9b48b507dcc).
    for table in ("bills", "bill_lines", "bill_line_modifiers"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_line_modifiers_shop_id'), table_name='bill_line_modifiers')
    op.drop_index(op.f('ix_bill_line_modifiers_bill_line_id'), table_name='bill_line_modifiers')
    op.drop_table('bill_line_modifiers')
    op.drop_index(op.f('ix_bill_lines_shop_id'), table_name='bill_lines')
    op.drop_index(op.f('ix_bill_lines_bill_id'), table_name='bill_lines')
    op.drop_table('bill_lines')
    op.drop_index(op.f('ix_bills_totals_mismatch'), table_name='bills')
    op.drop_index(op.f('ix_bills_shop_id'), table_name='bills')
    op.drop_index('ix_bills_shop_business_date', table_name='bills')
    op.drop_index(op.f('ix_bills_device_id'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
    # Hand-written: autogenerate never drops Postgres enum types.
    op.execute("DROP TYPE IF EXISTS payment_mode")
    op.execute("DROP TYPE IF EXISTS bill_status")
